[theme]
# Primary theme color - Professional blue gradient
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2d3748"
font = "sans serif"

[server]
# Increase upload size for file processing
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[client]
# Improve user experience
showErrorDetails = false
toolbarMode = "minimal"

[browser]
# Better URL handling
gatherUsageStats = false

[logger]
# Set appropriate logging level
level = "info"